### ISSUE TITLE
chart are not displaying with ESR firefox

### ISSUE THREAD

**Issue by mckaygerhard** [jfcherng-roundcube/plugin-quota#2]
no errors in console, only a garbage in the screen

![2018-01-05-124846_1280x1024_scrot](https://user-images.githubusercontent.com/1571724/34619684-55f7d3e4-f219-11e7-9027-b71cb5e927fc.png)

**Comment by mckaygerhard** [comment]
now tested agains firefox-lasted and got garbage also!

**Comment by jfcherng** [comment]
Is the `,`  being the decimal point (`.` in most countries)?

I have updated the `canvasjs.chart.js`. Please try the updated one.
Note that your browser may have cached js files so you have to clear the cache (<kbd>Ctrl</kbd>+<kbd>F5</kbd>).

**Comment by mckaygerhard** [comment]
PERFECT! many many thanks! seems works in RC 1.0 1.1, i'll test in 1.2 and 1.3 and report feedback
